import { App, normalizePath } from "obsidian";
import { Cluster } from "./clustering";
import { SemanticClusterSettings } from "./settings";

function safeFilename(name: string): string {
  return name.replace(/[\\/:*?"<>|]/g, "-");
}

export async function writeClusterNotes(
  app: App,
  settings: SemanticClusterSettings,
  clusters: Cluster[]
): Promise<void> {
  const dir = normalizePath(`${settings.pluginFolderName}/clusters`);

  if (!(await app.vault.adapter.exists(dir))) {
    await app.vault.createFolder(dir);
  }

  for (const cluster of clusters) {
    const memberLines = cluster.members
      .map((m) => `  - "[[${m.title}]]"`)
      .join("\n");

    const content = [
      "---",
      "cluster-members:",
      memberLines,
      `cluster-size: ${cluster.members.length}`,
      `similarity-threshold: ${settings.similarityThreshold}`,
      "---",
      "",
      "*Auto-generated by Semantic Cluster Plugin. Do not edit manually.*",
    ].join("\n");

    const filePath = normalizePath(
      `${dir}/${safeFilename(cluster.name)}.md`
    );
    await app.vault.adapter.write(filePath, content);
  }
}
