import { App, normalizePath, TFile, TFolder } from "obsidian";
import { SemanticClusterSettings } from "./settings";

// "Projects/Active" → "Projects — Active"
// root (parent === null) → "_root"
function folderToStem(folder: TFolder): string {
  if (folder.parent === null) return "_root";
  return folder.path.replace(/\//g, " — ");
}

export async function writeFolderNotes(
  app: App,
  settings: SemanticClusterSettings
): Promise<number> {
  const outputDir = normalizePath(
    `${settings.pluginFolderName}/folder-notes`
  );

  if (!(await app.vault.adapter.exists(outputDir))) {
    await app.vault.createFolder(outputDir);
  }

  const excluded = new Set([settings.pluginFolderName, ".obsidian"]);
  let count = 0;

  async function processFolder(folder: TFolder): Promise<void> {
    const isRoot = folder.parent === null;

    const childFiles: TFile[] = [];
    const childFolders: TFolder[] = [];

    for (const child of folder.children) {
      if (child instanceof TFile && child.extension === "md") {
        childFiles.push(child);
      } else if (child instanceof TFolder && !excluded.has(child.name)) {
        childFolders.push(child);
      }
    }

    if (!isRoot || settings.generateRootNote) {
      const folderPath = isRoot ? "/" : folder.path;

      const fileSection =
        childFiles.length > 0
          ? "folder-files:\n" +
            childFiles.map((f) => `  - "[[${f.basename}]]"`).join("\n")
          : "folder-files: []";

      const subSection =
        childFolders.length > 0
          ? "folder-subfolders:\n" +
            childFolders
              .map((f) => `  - "[[${folderToStem(f)}]]"`)
              .join("\n")
          : "folder-subfolders: []";

      const content = [
        "---",
        `folder-path: "${folderPath}"`,
        fileSection,
        subSection,
        "---",
        "",
        "*Auto-generated by Semantic Cluster Plugin. Do not edit manually.*",
      ].join("\n");

      const filename = folderToStem(folder) + ".md";
      await app.vault.adapter.write(
        normalizePath(`${outputDir}/${filename}`),
        content
      );
      count++;
    }

    for (const child of childFolders) {
      await processFolder(child);
    }
  }

  await processFolder(app.vault.getRoot());
  return count;
}
